name: Ensure Version Bump

on:
  pull_request:
    branches: [main]

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get package.json from main
        run: |
          git fetch origin main
          git show origin/main:package.json > package-main.json

      - name: Compare versions
        run: |
          old_version=$(jq -r .version package-main.json)
          new_version=$(jq -r .version package.json)

          echo "Main branch version: $old_version"
          echo "PR branch version:   $new_version"

          if [ "$old_version" = "$new_version" ]; then
            echo "❌ Version not bumped! Please update package.json"
            exit 1
          fi

          echo "✅ Version bump detected"
