name: Publish to npm

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - run: rm -rf node_modules package-lock.json
      - run: npm install
      - run: npm run build

      # If it's a tag (release) → publish to "latest"
      - name: Publish release
        if: startsWith(github.ref, 'refs/tags/v')
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # If it's a PR → publish a pre-release with unique tag
      - name: Publish PR preview
        if: github.event_name == 'pull_request'
        run: |
          # Example version: 1.2.3-pr.123.0
          PR_VERSION=$(node -p "require('./package.json').version + '-pr.${{ github.event.number }}.${{ github.run_number }}'")
          npm version $PR_VERSION --no-git-tag-version
          npm publish --tag pr-${{ github.event.number }} --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
